### ISSUE TITLE
인더섬 기획

### ISSUE THREAD

**Issue by Hansanghyeon** [peterosea/inthesum#1]
## TODOs

디자인이 완료된 기준으로 작성

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #36
- [x] #23
- [x] #33
- [x] #24
- [x] #34
- [x] #26
- [x] #32
- [x] #28
- [x] #35
- [x] #30

## 퍼블리싱 디테일

- [ ] 메인페이지 매거진슬라이드 모바일에서 2줄 (m)

## 퍼블리싱 기능

- [x] Shrink hook
- [ ] video.js play button
- [ ] keen slider pagination progress bar

## 디자인 수정 반영

> 확실하게 모두 옮기지 않았음

- [x] 메인페이지

**Comment by Hansanghyeon** [comment]
- [ ] 메인슬라이더 블러이미지 딤드 누락된 곳이있는 것같음
- [ ] 메인슬라이더 키비주얼 버튼 분리 (컴포넌트) (기능이 많음)
- [ ] 메인 매거진 슬라이더 keen slider 제거 그냥 스크롤로 변경 (option)

**Comment by Hansanghyeon** [comment]
#51
